"""Adds password into organizations.

Revision ID: d3bc93a496e7
Revises: 2df5a80c1875
Create Date: 2024-06-16 00:50:32.608695+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3bc93a496e7"
down_revision: Union[str, None] = "2df5a80c1875"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("password", sa.Unicode(length=128), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "password")
    # ### end Alembic commands ###
