"""Adds index for organizations.name.

Revision ID: ffd4a11eb3e1
Revises: 70f64e8a3785
Create Date: 2024-06-16 23:24:30.849089+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffd4a11eb3e1"
down_revision: Union[str, None] = "70f64e8a3785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name", table_name="organizations")
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.create_index("name", "organizations", ["name"], unique=True)
    # ### end Alembic commands ###
